var options = {
  adsafe: false,
  bitwise: true,
  browser: true,
  cap: false,
  confusion: false,
  continue: true,
  css: false,
  debug: false,
  devel: true,
  eqeq: false,
  es5: true,
  evil: false,
  forin: false,
  fragment: false,
  indent: 2,
  maxerr: 300,
  maxlen: 80,
  newcap: true,
  node: true,
  nomen: true,
  on: false,
  passfail: false,
  plusplus: false,
  predef: [
    "d3",
    "require",
    "define",
    "_",
    "$",
    "describe",
    "it",
    "expect",
    "after",
    "afterEach",
    "before",
    "beforeEach",
    // Some specific things available within xChart's scope only
    "_vis",
    "_scales",
    "_visutils",
    "xChart"
  ],
  regexp: true,
  rhino: false,
  safe: false,
  sloppy: true,
  sub: false,
  undef: false,
  unparam: false,
  vars: false,
  white: false,
  widget: false,
  windows: false
};
